// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8XAgeZvAFC98sCfPsWddudH7IVC3f8xg',
    appId: '1:739501948136:web:e064a3ee96a502f0851d5d',
    messagingSenderId: '739501948136',
    projectId: 'prompta-ai-demo',
    authDomain: 'prompta-ai-demo.firebaseapp.com',
    storageBucket: 'prompta-ai-demo.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtotca_Hq0cbl8CUQwva5Hevzwo3z6noM',
    appId: '1:739501948136:android:90898ffc28340e65851d5d',
    messagingSenderId: '739501948136',
    projectId: 'prompta-ai-demo',
    storageBucket: 'prompta-ai-demo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAi5xUH2VvYdadOVisd-WeUxF22W40mmU8',
    appId: '1:739501948136:ios:ff4bf641e8d3f840851d5d',
    messagingSenderId: '739501948136',
    projectId: 'prompta-ai-demo',
    storageBucket: 'prompta-ai-demo.firebasestorage.app',
    iosBundleId: 'com.example.client',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAi5xUH2VvYdadOVisd-WeUxF22W40mmU8',
    appId: '1:739501948136:ios:ff4bf641e8d3f840851d5d',
    messagingSenderId: '739501948136',
    projectId: 'prompta-ai-demo',
    storageBucket: 'prompta-ai-demo.firebasestorage.app',
    iosBundleId: 'com.example.client',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8XAgeZvAFC98sCfPsWddudH7IVC3f8xg',
    appId: '1:739501948136:web:8012006da8529633851d5d',
    messagingSenderId: '739501948136',
    projectId: 'prompta-ai-demo',
    authDomain: 'prompta-ai-demo.firebaseapp.com',
    storageBucket: 'prompta-ai-demo.firebasestorage.app',
  );
}
